### ISSUE TITLE
Erro QR Code

### ISSUE THREAD

**Issue by ricfrenov** [ldurans/izing.io#219]
Boa noite Pessoal, estou tendo esse erro no backend na geração do QR Code sem falar que quando gera o qr code não consigo ler, o node deve ser a versão 20 mesmo?

Erro:
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
at ServerResponse.setHeader (node:_http_outgoing:659:11)
at ServerResponse.header (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\response.js:795:10)
at ServerResponse.send (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\response.js:175:12)
at ServerResponse.json (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\response.js:279:15)
at C:\Users\ricfr\WhatsApp\izing.open.io\backend\dist\app\modules.js:88:36
at Generator.next ()
at C:\Users\ricfr\WhatsApp\izing.open.io\backend\dist\app\modules.js:31:71
at new Promise ()
at __awaiter (C:\Users\ricfr\WhatsApp\izing.open.io\backend\dist\app\modules.js:27:12)
at C:\Users\ricfr\WhatsApp\izing.open.io\backend\dist\app\modules.js:77:39
at newFn (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express-async-errors\index.js:16:20)
at Layer.handle_error (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\layer.js:71:5)
at trim_prefix (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:326:13)
at C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:286:9
at Function.process_params (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:346:12)
at next (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:280:10)
at C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules@sentry\node\dist\handlers.js:201:17
at Hub.withScope (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules@sentry\hub\dist\hub.js:88:13)
at callOnHub (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules@sentry\minimal\dist\index.js:18:28)
at Object.withScope (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules@sentry\minimal\dist\index.js:163:5)
at sentryErrorMiddleware (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules@sentry\node\dist\handlers.js:191:20)
at newFn (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express-async-errors\index.js:16:20)
at Layer.handle_error (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\layer.js:71:5)
at trim_prefix (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:326:13)
at C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:286:9
at Function.process_params (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:346:12)
at Domain.next (C:\Users\ricfr\WhatsApp\izing.open.io\backend\node_modules\express\lib\router\index.js:280:10)
at Domain.emit (node:events:519:28)
info: 2024-08-17T22:25:00.026Z FindUpdateTicketsInactiveChatBot Initiated
info: 2024-08-17T22:25:00.028Z SendMessageSchenduled Initiated
info: 2024-08-17T22:25:00.036Z Finalized FindUpdateTicketsInactiveChatBot
info: 2024-08-17T22:25:00.038Z Finalized SendMessageSchenduled

![image](https://github.com/user-attachments/assets/d5229e55-f938-4f8d-8ae5-3ebd154d31a0)

**Comment by andifilhohub** [comment]
node na versão 16, amigo

**Comment by linuxangra** [comment]
Versão 16.13.2?

**Comment by custodianAlisonHenri** [comment]
consegui rodar na v18.20.2; mas precisei atualizar algumas dependências;

**Comment by miguelbispo** [comment]
@custodianAlisonHenri quais foram as dependências que você atualizou? Estava funcionando perfeitamente com o node 18.20 até algumas horas atrás e do nada parou.

**Comment by ecajueiroafpes** [comment]
Algúem consegui resolver? estou com uma instalação nova com esse problema aqui

**Comment by JhordanEdyvald** [comment]
Consegui resolver o problema. Vou tentar subir um pull request mais tarde.

**Comment by herichmarcelo** [comment]
@JhordanEdyvald acabei de pegar esse erro tem algum passo para resolver?

**Comment by JhordanEdyvald** [comment]
@herichmarcelo @ecajueiroafpes @miguelbispo @custodianAlisonHenri @linuxangra @ricfrenov 

O erro está no pacote whatsapp_web.js. O Idurans colocou um fork dele que está desatualizado no package json.
Vão no arquivo /backend/package.json e procurem por:

"whatsapp-web.js": "github:ldurans/whatsapp-web.js#webpack-exodus",

E troquem por:

"whatsapp-web.js": "^1.34.1",

Ai vocês vão salvar e dar um "npm run build" no backend, depois só startar "npm start"
