### ISSUE TITLE
Erro npm start

### ISSUE THREAD

**Issue by Silvioerick** [ldurans/izing.io#44]
deploy@izing:~/izing/backend$ npm start

> backend@1.0.0 start /home/deploy/izing/backend
> nodemon --inspect  dist/server.js

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --inspect dist/server.js`
Debugger listening on ws://127.0.0.1:9229/ae17bdd8-b332-4b8b-951c-8127e4ab0075
For help, see: https://nodejs.org/en/docs/inspector
info: 2022-11-14T15:48:11.753Z Server started on port: 3000
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
Error: Error initializing Lua scripts
    at /home/deploy/izing/backend/node_modules/bull/lib/queue.js:153:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40370) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
Error: Error initializing Lua scripts
    at /home/deploy/izing/backend/node_modules/bull/lib/queue.js:153:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
Error: Error initializing Lua scripts
    at /home/deploy/izing/backend/node_modules/bull/lib/queue.js:153:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
Error: Error initializing Lua scripts
    at /home/deploy/izing/backend/node_modules/bull/lib/queue.js:153:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
Error: Error initializing Lua scripts
    at /home/deploy/izing/backend/node_modules/bull/lib/queue.js:153:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
Error: Error initializing Lua scripts
    at /home/deploy/izing/backend/node_modules/bull/lib/queue.js:153:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
Error: Error initializing Lua scripts
    at /home/deploy/izing/backend/node_modules/bull/lib/queue.js:153:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '3' ] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
(node:40370) UnhandledPromiseRejectionWarning: ReplyError: NOAUTH Authentication required.
    at parseError (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/deploy/izing/backend/node_modules/redis-parser/lib/parser.js:302:14)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 21)
(node:40370) UnhandledPromiseRejectionWarning: Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/home/deploy/izing/backend/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
(node:40370) UnhandledPromiseRejectionWarning: Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/home/deploy/izing/backend/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)
(node:40370) UnhandledPromiseRejectionWarning: Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/home/deploy/izing/backend/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)
(node:40370) UnhandledPromiseRejectionWarning: Error: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (/home/deploy/izing/backend/node_modules/amqplib/lib/connection.js:260:17)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:40370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 25)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Silvioerick** [comment]
Resolvido, estava usando redis com senha, add as seguinte linha nos arquivos abaixo :

password: process.env.IO_REDIS_PASSWORD || undefined,

backend/src/libs
     Queue.ts
     redisCliente.ts
     socket.ts

**Comment by ldurans** [comment]
Atualmente não cobrimos o redis com utilização do password. Disponibilizaremos essa funcionalidade nas próximas versões.
