### ISSUE TITLE
whatsapp-wb.js error

### ISSUE THREAD

**Issue by dlpazinatto** [ldurans/izing.io#53]
Nao estou conseguindo criar o qrcode para whatsapp, nos logs do back aparece:

error: 2022-11-16T14:20:04.095Z ERROR: checkMessages Tenant: 1:: Cannot read property 'evaluate' of null - TypeError: Cannot read property 'evaluate' of null
0|izing-backend  |     at Client.getState (/home/deploy/izing.io/backend/node_modules/whatsapp-web.js/src/Client.js:845:35)
0|izing-backend  |     at /home/deploy/izing.io/backend/src/libs/wbot.ts:31:49
0|izing-backend  |     at Generator.next (<anonymous>)
0|izing-backend  |     at /home/deploy/izing.io/backend/dist/libs/wbot.js:8:71
0|izing-backend  |     at new Promise (<anonymous>)
0|izing-backend  |     at __awaiter (/home/deploy/izing.io/backend/dist/libs/wbot.js:4:12)
0|izing-backend  |     at Timeout.checkMessages [as _onTimeout] (/home/deploy/izing.io/backend/src/libs/wbot.ts:29:74)
0|izing-backend  |     at listOnTimeout (internal/timers.js:559:11)
0|izing-backend  |     at processTimers (internal/timers.js:500:7)

Tem alguma informação sobre este erro?

Obrigado

**Comment by dlpazinatto** [comment]
Resolvi. Era problema no meu ambiente
